### ISSUE TITLE
Not able to change program

### ISSUE THREAD

**Issue by bjornand1** [andyno/homebridge-millheat#1]
Hi, I have one Mill WiFi heater and two Mill Wifi Sockets (all three have been assigned to rooms and heating programs chosen). I have tried to get these to work in HomeKit using both the Homey app/Homeykit and this Homebridge plugin.

In both cases, the current temperature is sent correctly to the Home app, but changing the temperature or program in the Home app has no effect on the actual settings in the Millheat app. This means I cannot set up automations in HomeKit (I want to turn them off when window sensors detect an open window).

Is this simply something that is not possible or is there a trick I haven't discovered?

**Comment by andyno** [comment]
It is possible. To accomplish this you should set the device to independent mode. To get this working in the Home app (i assume on iPhone/iOS) you should set the heater to Heat instead of Auto, Auto will follow the room program. You can try to set it to Heat and then check in the mill app, it should be in independent mode. Changing the temperature then should set the target temperature

**Comment by bjornand1** [comment]
Hei, Andreas, jeg kan gjerne skrive på norsk til deg?

Testet dette, ser at det virker slik du sier, ja. Men det jeg egentlig ville oppnå er 1) at Mill egentlig kan få styre ovnen basert på program satt opp i Mill-appen 2) at HomeKit kan slå av ovnen når vindussensor detekterer åpnet vindu (og på igjen når det lukkes).

Er det mulig å få til dette, tror du?

Mvh
Bjørn

**Comment by andyno** [comment]
Ja, burde vel det. Tror du bare kan sette den til Av i Home appen når vinduet er åpent, og så tilbake til Auto når vinduet er igjen. Tror jeg da. Jeg har ikke fått testet plugin'en så mye enda, så er ikke sikker på om alt fungerer

**Comment by bjornand1** [comment]
Takk for raskt svar! Men da er en forutsetning at enhetene (jeg har to plugger og en ovn) ikke er tilegnet et rom i Mill-appen, slik at de fremstår som «Independent devices»?

Sendt fra min iPad Pro

**Comment by andyno** [comment]
Nei, pluginen skal fikse det for det. Så den setter de til off når du setter til Av i appen. Jeg har kun ovner, så jeg har ikke testet med plugger. Når jeg setter til off i appen og ser på ovnen ser jeg at det står "OF" i displayet

**Comment by bjornand1** [comment]
Hei igjen, takk for oppfølging.

Har undersøkt litt nærmere, og ovnen, der jeg kan se på displayet hva som skjer, synes å virke slik det skal (men i blant oppdateres ikke status i Millheat-appen, selv om displayet viser at den slås av/endres program).

For pluggene er det litt verre, her er det jo ikke noe display som viser hva som skjer, men ut fra klikk for på/av kan det virke som det også fungerer der, men med inkonsistens i oppdatering av status i Millheat-appen.

Jeg har også en Homey-app for Mill, der får man frem alle programmene slik de benevnes i Millheat-appen og der er oppdateringen begge veier mye raskere. Bruker jeg dog Homeykit for å få Mill-enhetene over i HomeKit på den måten er det tilsvarende som via Homebridge. Skyldes kanskje at HomeKit ikke støtter alle Mill sine programmer?

Mvh
Bjørn

**Comment by andyno** [comment]
Uten at jeg har sett så mye på det, kunne jeg ikke finne noen god måte å oversette det til HomeKit sin standard nei. Tror hvis man skal bruke homekit så må man la homekit styre programmet helt, altså at ovnen alltid står i independent mode og homekit setter temperaturen.

**Comment by bjornand1** [comment]
Takk uansett for at du (og mange andre) investerer tid i plugins!
