### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kims89** [andyno/homebridge-millheat#5]
Hello, strugling with UnhandledPromiseRejectionWarning.

The config I use is simular to the default example.

`{
            "platform": "millheat",
            "name": "millheat",
            "username" : "your@email",
            "password": "hunter2",
            "ignoreDevices": []
        }`

Error:
`(node:18552) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at MillPlatform.getAllHeaters (/usr/local/lib/node_modules/homebridge-millheat/src/platform.js:50:54)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at MillPlatform.accessories (/usr/local/lib/node_modules/homebridge-millheat/src/platform.js:77:21)
(node:18552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by brodyhoskins** [comment]
I'm noticing this as well:

```console
$ node -v
v14.5.0
```

Error:
```console
(node:371166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:371166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by karlwhite** [comment]
@kims89 @brodyhoskins I believe I've found the cause/a workaround for this... assuming your situation is the same as mine, I receive this error if I have any rooms configured in the Mill app with no devices inside. Once I deleted all empty rooms, the error goes away, and Homebridge starts up correctly.

**Comment by kims89** [comment]
Thanks @karlwhite! That did the trick!🤙
